apiVersion: v1
data:
  APPDYNAMICS_AGENT_APPLICATION_NAME: "eCommerce"
  APPDYNAMICS_AGENT_ACCOUNT_NAME: "activesec"
  APPDYNAMICS_CONTROLLER_HOST_NAME: "https://activesec.saas.appdynamics.com/controller/"
  APPDYNAMICS_CONTROLLER_PORT: "443"
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: "true"
  APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "4e91f2713d0c"
  APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME: "true"
  APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX: "<value>"
  EVENT_ENDPOINT: "https://analytics.api.appdynamics.com/"
  APPDYNAMICS_AGENT_GLOBAL_ACCOUNT_NAME: "Activesec_10b5e9f5-fee4-482a-a893-a32da826ad7d"
  APPDYNAMICS_EVENT_API_KEY: "3390a87e-99c8-433c-8e98-98a5c883f17c"
kind: ConfigMap
metadata:
  name: as-java-config